
int main(const int argc, char** argv)
{
	try {

		return 0;
	} catch (const std::exception& ex) {

		return 1;
	} catch (...) {

		return 1;
	}
}
